#spring  setup and common configuration
spring:
  profiles:
    active: local

server:
  port: 8099

---
#spring profiles : LOCAL
#spring and hikari setup
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/wkimdev
  
#datasource:
#  session: 
#    store-type: REDIS
#  redis:
#    host: 192.168.0.242
#    port: 6379
#    password: dc393939
    
#logging
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        